// Code generated by SQLBoiler 4.14.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbmodel

var TableNames = struct {
	Alerts                       string
	CCTVDevices                  string
	DeviceTokens                 string
	Premises                     string
	SchemaMigrations             string
	Users                        string
	VerificationRequestResponses string
	VerificationRequests         string
}{
	Alerts:                       "alerts",
	CCTVDevices:                  "cctv_devices",
	DeviceTokens:                 "device_tokens",
	Premises:                     "premises",
	SchemaMigrations:             "schema_migrations",
	Users:                        "users",
	VerificationRequestResponses: "verification_request_responses",
	VerificationRequests:         "verification_requests",
}
