// Code generated by mockery v2.20.0. DO NOT EDIT.

package alerts

import (
	context "context"

	kafka "github.com/nhan1603/CloneScc/api/internal/pkg/kafka"
	mock "github.com/stretchr/testify/mock"

	model "github.com/nhan1603/CloneScc/api/internal/model"

	websocket "github.com/gorilla/websocket"
)

// MockController is an autogenerated mock type for the Controller type
type MockController struct {
	mock.Mock
}

// BroadCast provides a mock function with given fields: ctx, conn
func (_m *MockController) BroadCast(ctx context.Context, conn *websocket.Conn) {
	_m.Called(ctx, conn)
}

// CreateAlert provides a mock function with given fields: ctx, alertInstance
func (_m *MockController) CreateAlert(ctx context.Context, alertInstance model.AlertMessage) (int64, error) {
	ret := _m.Called(ctx, alertInstance)

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.AlertMessage) (int64, error)); ok {
		return rf(ctx, alertInstance)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.AlertMessage) int64); ok {
		r0 = rf(ctx, alertInstance)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.AlertMessage) error); ok {
		r1 = rf(ctx, alertInstance)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Detail provides a mock function with given fields: _a0, _a1
func (_m *MockController) Detail(_a0 context.Context, _a1 int64) (model.Alert, error) {
	ret := _m.Called(_a0, _a1)

	var r0 model.Alert
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (model.Alert, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) model.Alert); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(model.Alert)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HandleMessage provides a mock function with given fields: ctx, msg
func (_m *MockController) HandleMessage(ctx context.Context, msg kafka.ConsumerMessage) error {
	ret := _m.Called(ctx, msg)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, kafka.ConsumerMessage) error); ok {
		r0 = rf(ctx, msg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// List provides a mock function with given fields: _a0, _a1
func (_m *MockController) List(_a0 context.Context, _a1 model.GetAlertsInput) ([]model.Alert, int64, error) {
	ret := _m.Called(_a0, _a1)

	var r0 []model.Alert
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, model.GetAlertsInput) ([]model.Alert, int64, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.GetAlertsInput) []model.Alert); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Alert)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.GetAlertsInput) int64); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, model.GetAlertsInput) error); ok {
		r2 = rf(_a0, _a1)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Push provides a mock function with given fields: ctx, m
func (_m *MockController) Push(ctx context.Context, m model.AlertMessage) {
	_m.Called(ctx, m)
}

type mockConstructorTestingTNewMockController interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockController creates a new instance of MockController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockController(t mockConstructorTestingTNewMockController) *MockController {
	mock := &MockController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
