// Code generated by mockery v2.20.0. DO NOT EDIT.

package alert

import (
	context "context"

	model "github.com/nhan1603/CloneScc/api/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

// CreateAlert provides a mock function with given fields: ctx, dataModel, cctvDeviceID
func (_m *MockRepository) CreateAlert(ctx context.Context, dataModel model.AlertMessage, cctvDeviceID int64) (int64, error) {
	ret := _m.Called(ctx, dataModel, cctvDeviceID)

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.AlertMessage, int64) (int64, error)); ok {
		return rf(ctx, dataModel, cctvDeviceID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.AlertMessage, int64) int64); ok {
		r0 = rf(ctx, dataModel, cctvDeviceID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.AlertMessage, int64) error); ok {
		r1 = rf(ctx, dataModel, cctvDeviceID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAlert provides a mock function with given fields: _a0, _a1
func (_m *MockRepository) GetAlert(_a0 context.Context, _a1 int64) (model.Alert, error) {
	ret := _m.Called(_a0, _a1)

	var r0 model.Alert
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (model.Alert, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) model.Alert); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(model.Alert)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAlerts provides a mock function with given fields: _a0, _a1
func (_m *MockRepository) GetAlerts(_a0 context.Context, _a1 model.GetAlertsInput) ([]model.Alert, int64, error) {
	ret := _m.Called(_a0, _a1)

	var r0 []model.Alert
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, model.GetAlertsInput) ([]model.Alert, int64, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.GetAlertsInput) []model.Alert); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Alert)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.GetAlertsInput) int64); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, model.GetAlertsInput) error); ok {
		r2 = rf(_a0, _a1)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

type mockConstructorTestingTNewMockRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockRepository(t mockConstructorTestingTNewMockRepository) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
